### ISSUE TITLE
Improvement in the UI/UX.

### ISSUE THREAD

**Issue by div-bargali** [div-bargali/Echoes-MERN-project#3]
Any changes on the UI/UX to make the overall experience smooth are appreciated.

**Comment by AkhilChoubey** [comment]
I would like to work on this , I will add some styling to the texts and will add some onscroll animation for the overall inhancement of the project .. please assign this issue to me ..

**Comment by AkhilChoubey** [comment]
Also , please add hacktoberfest-accepted label for this issue.

**Comment by div-bargali** [comment]
> I would like to work on this , I will add some styling to the texts and will add some onscroll animation for the overall inhancement of the project .. please assign this issue to me ..

You can start working on it. Thanks.
